### ISSUE TITLE
Magic-search not using all friend lists 

### ISSUE THREAD

**Issue by marcotenrinho** [BelledonneCommunications/liblinphone#153]
Hello,

I am trying to use MagicSearch to search through a friend list besides the default one and found that I can't do it. 
1. I could not find how to change the default friend list - I don't think it is possible?
2. Magic search uses just one of the friend lists. See bellow the code and my suggestion.

As you can see in the code bellow, magic search gets the default friend list and iterates through that list. 

My suggestion is that the for loop gets transformed in a nested loop - external loop iterates through friend lists and internal one through the friends in each list. Would this make sense?

```
list<SearchResult> *MagicSearch::beginNewSearch (const string &filter, const string &withDomain) const {
	list<SearchResult> clResults, crResults;
	list<SearchResult> *resultList = new list<SearchResult>();
	LinphoneFriendList *fList = linphone_core_get_default_friend_list(this->getCore()->getCCore());

	// For all friends or when we reach the search limit
	for (bctbx_list_t *f = fList->friends ; f != nullptr ; f = bctbx_list_next(f)) {
		list<SearchResult> fResults = searchInFriend(reinterpret_cast<LinphoneFriend*>(f->data), filter, withDomain);
		addResultsToResultsList(fResults, *resultList);
	}
```

Thanks in advance!

**Comment by Viish** [comment]
Hello,
Thanks for the report. This is indeed an issue.
Here's the fix (will be merged into master and release branches soon): 
```
commit 6918b18c1c53667e89df667b32880affd5477d4a
Author: Sylvain Berfini <sylvain.berfini@belledonne-communications.com>
Date:   Mon Jun 1 12:56:14 2020 +0200
    Improved magic search to look into all friends lists and not just the default one
```

Cheers,
