### ISSUE TITLE
getCallHistoryForAddress doesn't exist

### ISSUE THREAD

**Issue by driesken** [BelledonneCommunications/liblinphone#154]
Hi,

Is it possible that the method getCallHistoryForAddress is missing? "getCallHistory" does exist however.

```
HistoryDetailFragment.java:203: error: cannot find symbol
logs = core.getCallHistoryForAddress(address);
```

**Comment by Viish** [comment]
Hi,
Yes it was deprecated for some time and was removed yesterday.
Use core.getCallHistory(address, local_address) instead.
Cheers,

**Comment by driesken** [comment]
Thanks, I've noticed this issue in the Android master after building
Regards
