### ISSUE TITLE
Core.interpretUrl(String s) not working properly

### ISSUE THREAD

**Issue by Cullian2017** [BelledonneCommunications/liblinphone#156]
I am using the SDK version 4.4.0, when I tried to make the call, we found core.interpretUrl(String s) return the wrong invite address. Here are the details:
![20200818200322](https://user-images.githubusercontent.com/32505998/90510796-258fad00-e18e-11ea-8ec0-3366c32de4d6.png)

call a number with prefix 005555 will cause this problem, while call a number without 005555 is working well. Does anyone have the same problem?

**Comment by Viish** [comment]
005555 isn't a valid international prefix. 0055 is (for Brazil), and it allows only 11 digits after it.
86 is the Chinese prefix that also allows for 11 digits so everything is fine in your second example. However for the interpretUrl to add the + in front of it I guess you have configured your proxy config with the 86 country prefix ?

**Comment by Cullian2017** [comment]
Dear Viish,
Thank for your prompt response.

The problem is why interpretUrl not adding + in front of 005555? i configured proxy config with the same prefix 005555
