### ISSUE TITLE
Need a (documented) setting to configure custom CAs per proxy

### ISSUE THREAD

**Issue by systemcrash** [BelledonneCommunications/liblinphone#162]
Either a "ignore CA" (and connect via TLS, whichever CA - or cert - is presented)

Or a per proxy setting to specify a .pem file

On macOS, I can modify the `rootca.pem` file in the app. On linux, not sure. But windows..... tried the "import cert into windows CA store" - didn't work. Should Linphone for windows use that?

Tried editing the `linphonerc` file as so as found [here ](https://wiki.linphone.org/xwiki/wiki/public/view/Flexisip/Configuration/TLS%20settings/):
```
[global]
transports=sips:sip.example.org sips:sip2.example.org sips:sip.other-domain.com;tls-certificates-dir=/etc/flexisip/tls/other-domain.com
tls-certificates-dir=%LOCALAPPDATA%/linphone
```

But the settings don't 'take'. The above are for Flexisip, and not (lib)linphone. 

Please document or add and document a setting to specify custom certs per proxy.

**Comment by Viish** [comment]
You can set the path to your own certificates using either `linphone_core_set_user_certificates_path()` or in the config file:
```
[misc]
user_certificates_path=<path>
```

**Comment by Viish** [comment]
You can also change the root_ca in the config file and/or disable certificates verification:
```
[sip]
root_ca=<path>
verify_server_certs=1
verify_server_cn=1
```

**Comment by systemcrash** [comment]
Ah - thank you - can someone please document this?

https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/

> You can also change the root_ca in the config file and/or disable certificates verification:
> 
> ```
> [sip]
> root_ca=<path>
> verify_server_certs=1
> verify_server_cn=1
> ```

Caveat - global setting... per proxy setting for these is the goal for this issue. Granularity. 

You compromise security for all proxies when just one uses a custom cert using this route. 

> You can set the path to your own certificates using either `linphone_core_set_user_certificates_path()` or in the config file:
> 
> ```
> [misc]
> user_certificates_path=<path>
> ```

Also global (located globally), but TLS will sort the wheat from the chaff. Having one or both of these settings per proxy. I've used linphone for a while, but with each new version the config file location changes. I also had to search the web to find where the `linphonerc` file lives. Not ideal. So having these in the GUI one day would be nice (yes, I know this is liblinphone).

**Comment by Viish** [comment]
>  I also had to search the web to find where the linphonerc file lives. Not ideal.

Yes our configuration file isn't really well documented yet, but that will improve as time goes byour focus currently being in on the API methods.

> Caveat - global setting... per proxy setting for these is the goal for this issue. Granularity.

As it is a directory for where to store certificates, one is enough to store multiple certificates for all your configs.

> I've used linphone for a while, but with each new version the config file location changes.

That isn't true are we are taking care of always taking care of backward compatibility.

Also, if you need a client certificate for client authentication, you can set one per LinphoneAuthInfo:
```
[auth_info_0]
client_cert_chain=
client_cert_key=
client_cert_key_passsword=
```

**Comment by systemcrash** [comment]
This should also go in the wiki - 😄 

To use a self-signed cert, which, say, doesn't match the Proxy registrar domain, you must enable a global setting to ignore the CN. 


I understand that the CN should not be used, and instead, the sAN Domain. But.. imperfect world. 



> Also, if you need a client certificate for client authentication, you can set one per LinphoneAuthInfo:
> 
> ```
> [auth_info_0]
> client_cert_chain=
> client_cert_key=
> client_cert_key_passsword=
> ```

This does not match the other stuff there...:
https://wiki.linphone.org/xwiki/wiki/public/view/Linphone/TLS%20client%20authentication/

**Comment by fuine6** [comment]
Can this ignore the CN of self -signature certificates, but verify in other cases?
