### ISSUE TITLE
Release tarball version 4..4.21 seems to contain the files from version 4.4.17

### ISSUE THREAD

**Issue by jschleus** [BelledonneCommunications/liblinphone#164]
I downloaded the file  https://github.com/BelledonneCommunications/liblinphone/archive/4.4.21.tar.gz and found that the contents of that tarball is identical to the tarball https://github.com/BelledonneCommunications/liblinphone/archive/4.4.17.tar.gz. But the GitHub repository contains in the meantime some changed files (e.g. src/address/identity-address.cpp). Is that the intention or is it an error?

**Comment by Viish** [comment]
Hi,
Yes this is expected, as there was no changes in liblinphone project between tags 4.4.17 and 4.4.21.
Cheers,

**Comment by jschleus** [comment]
Ok, sorry, ow I found the identical commit IDs for that releases. But out of curiosity, may I ask why such releases with different version numbers were released. That sees a bit unusual to me..

**Comment by Viish** [comment]
Actually it just to be aligned with SDK repository tag.

**Comment by jschleus** [comment]
Ah, thank you, now I understand and am reassured.
