### ISSUE TITLE
Crash app when start call

### ISSUE THREAD

**Issue by AlirezaDaryani** [BelledonneCommunications/liblinphone#167]
In my app, I used lib without any issues, but from yesterday suddenly app crash when call start with this backtrace :

`backtrace:
      #00 pc 005634e5  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::SalOp::release()+39) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #01 pc 004c70ad  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::CallSession::terminate(_LinphoneErrorInfo const*)+507) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #02 pc 004711d3  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::Call::terminate(_LinphoneErrorInfo const*)+77) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #03 pc 0044e9d7  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (linphone_call_terminate+98) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #04 pc 0069db1c  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (Java_org_linphone_core_CallImpl_terminate+36) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #05 pc 00144f67  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+71) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #06 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #07 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #08 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #09 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #10 pc 0068433c  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+700) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #11 pc 00138921  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #12 pc 00354b24  [anon:dalvik-classes.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk] (org.linphone.core.CallImpl.terminate+12)
      #13 pc 006837bc  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1980) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #14 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #15 pc 00002f10  [anon:dalvik-classes9.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk!classes9.dex] (com.ubtin.plugin.flutter_linphone_plugin.service.LinphoneService$1.onCallStateChanged+32)
      #16 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #17 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #18 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #19 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #20 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #21 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #22 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #23 pc 0055bc7a  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+474) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #24 pc 0040962f  /apex/com.android.runtime/lib/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+943) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #25 pc 003d8f44  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+1700) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #26 pc 003c53f9  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+73) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #27 pc 00619c06  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+62) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #28 pc 0068f17e  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #29 pc 0067c919  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (linphone_core_notify_call_state_changed+92) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #30 pc 0044b926  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (linphone_call_notify_state_changed+117) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #31 pc 00470a84  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::CallPrivate::onCallSessionStateChanged(std::__ndk1::shared_ptr<LinphonePrivate::CallSession> const&, LinphonePrivate::CallSession::State, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+698) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #32 pc 00470b52  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (non-virtual thunk to LinphonePrivate::CallPrivate::onCallSessionStateChanged(std::__ndk1::shared_ptr<LinphonePrivate::CallSession> const&, LinphonePrivate::CallSession::State, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+42) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #33 pc 004c3c13  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::CallSessionPrivate::setState(LinphonePrivate::CallSession::State, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+1749) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #34 pc 004d1fd6  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::MediaSessionPrivate::setState(LinphonePrivate::CallSession::State, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+166) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #35 pc 004ca014  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::CallSession::initiateOutgoing()+138) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #36 pc 004d9729  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::MediaSession::initiateOutgoing()+53) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #37 pc 0046e817  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (LinphonePrivate::CallPrivate::initiateOutgoing()+69) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #38 pc 00652a56  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (linphone_core_invite_address_with_params+1123) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #39 pc 006b0fa6  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/liblinphone.so (Java_org_linphone_core_CoreImpl_inviteAddressWithParams+203) (BuildId: 46cbae05a7c2bee9a1daa49f8476f4c26eed2683)
      #40 pc 00144f67  /apex/com.android.runtime/lib/libart.so (art_quick_generic_jni_trampoline+71) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #41 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #42 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #43 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #44 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #45 pc 0068433c  /apex/com.android.runtime/lib/libart.so (MterpInvokeDirect+700) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #46 pc 00138921  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #47 pc 0035f562  [anon:dalvik-classes.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk] (org.linphone.core.CoreImpl.inviteAddressWithParams+6)
      #48 pc 006837bc  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1980) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #49 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #50 pc 00002166  [anon:dalvik-classes9.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk!classes9.dex] (com.ubtin.plugin.flutter_linphone_plugin.FlutterLinphonePlugin.callMethod+82)
      #51 pc 00681adc  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+1612) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #52 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #53 pc 0000274e  [anon:dalvik-classes9.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk!classes9.dex] (com.ubtin.plugin.flutter_linphone_plugin.FlutterLinphonePlugin.onMethodCall+562)
      #54 pc 006837bc  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1980) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #55 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #56 pc 002cf656  [anon:dalvik-classes.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk] (io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage+34)
      #57 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #58 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #59 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #60 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #61 pc 02014e35  /memfd:/jit-cache (deleted) (io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart+469)
      #62 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #63 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #64 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #65 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #66 pc 006834ea  /apex/com.android.runtime/lib/libart.so (MterpInvokeInterface+1258) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #67 pc 00138a21  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_interface+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #68 pc 002c5c04  [anon:dalvik-classes.dex extracted in memory from /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/base.apk] (io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage+8)
      #69 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #70 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #71 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #72 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #73 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #74 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #75 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #76 pc 0055bc7a  /apex/com.android.runtime/lib/libart.so (art::InvokeVirtualOrInterfaceWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+474) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #77 pc 0040962f  /apex/com.android.runtime/lib/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+943) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #78 pc 003d8f44  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+1700) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #79 pc 003c53f9  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, char*)+73) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #80 pc 011973ed  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #81 pc 01197321  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #82 pc 011924b2  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #83 pc 01202cf1  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #84 pc 011a938f  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #85 pc 011abee5  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #86 pc 011abdf6  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #87 pc 011b257e  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #88 pc 011b25ac  /data/app/io.uptin.app-ex26JtGCHOLvqMPd5RhBXw==/lib/x86/libflutter.so (BuildId: 41b41257bd3fecb2110b68babe76fd09ee5a57bd)
      #89 pc 00018487  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+39) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #90 pc 00019414  /system/lib/libutils.so (android::Looper::pollInner(int)+1044) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #91 pc 00018f4e  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+62) (BuildId: 288ba3aff5b46dbd7e74be954af88b83)
      #92 pc 0013299b  /system/lib/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long long, int)+59) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #93 pc 002b86f8  /system/framework/x86/boot-framework.oat (art_jni_trampoline+136) (BuildId: ff6ec03dd8445d20788424c92ba8ea28ad0f54f4)
      #94 pc 02008ba6  /memfd:/jit-cache (deleted) (android.os.MessageQueue.next+230)
      #95 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #96 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #97 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #98 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #99 pc 0068186d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+989) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #100 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #101 pc 00319d8a  /system/framework/framework.jar (android.os.Looper.loop+130)
      #102 pc 00684f6c  /apex/com.android.runtime/lib/libart.so (MterpInvokeStatic+1260) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #103 pc 001389a1  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #104 pc 0018945e  /system/framework/framework.jar (android.app.ActivityThread.main+194)
      #105 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #106 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #107 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #108 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #109 pc 0013e9a2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #110 pc 00149a7a  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #111 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #112 pc 0055c32f  /apex/com.android.runtime/lib/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+1327) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #113 pc 004c9153  /apex/com.android.runtime/lib/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+83) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #114 pc 000c6bf8  /system/framework/x86/boot.oat (art_jni_trampoline+168) (BuildId: 7913dbaef2e8d9971cb7619ef0d566987f8326a7)
      #115 pc 0013e7d2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub+338) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #116 pc 00149a69  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+281) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #117 pc 00332502  /apex/com.android.runtime/lib/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+386) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #118 pc 0032c19c  /apex/com.android.runtime/lib/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+988) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #119 pc 0068186d  /apex/com.android.runtime/lib/libart.so (MterpInvokeVirtual+989) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #120 pc 00138821  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+33) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #121 pc 0034cd36  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #122 pc 002f8e0a  /apex/com.android.runtime/lib/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.12194892193087984976+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #123 pc 002ffcc5  /apex/com.android.runtime/lib/libart.so (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+181) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #124 pc 0066fbd9  /apex/com.android.runtime/lib/libart.so (artQuickToInterpreterBridge+1209) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #125 pc 0014503d  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+77) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #126 pc 00998b08  /system/framework/x86/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1816) (BuildId: ff6ec03dd8445d20788424c92ba8ea28ad0f54f4)
      #127 pc 0013e9a2  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_static_stub+418) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #128 pc 00149a7a  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+298) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #129 pc 0055a513  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+99) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #130 pc 0055a1ae  /apex/com.android.runtime/lib/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, char*)+430) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #131 pc 004305cd  /apex/com.android.runtime/lib/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+893) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #132 pc 003d93bf  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallMethodV(char const*, _JNIEnv*, _jobject*, _jclass*, _jmethodID*, char*, art::Primitive::Type, art::InvokeType)+2847) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #133 pc 003c7509  /apex/com.android.runtime/lib/libart.so (art::(anonymous namespace)::CheckJNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, char*)+73) (BuildId: 895645e5113da057f27d9b2ec11eb3bf)
      #134 pc 000b25fe  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+62) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #135 pc 000b628a  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+794) (BuildId: 6ceb9761bceb97a18c92f8a4b7072247)
      #136 pc 00003632  /system/bin/app_process32 (main+1490) (BuildId: b7a60bc7d078521421fd5a8d201915ae)
      #137 pc 000898e8  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+120) (BuildId: 76290498408016ad14f4b98c3ab6c65c)
Lost connection to device.
`

**Comment by Viish** [comment]
Please attach SDK logs from start of the app to the moment it crashes.

**Comment by Viish** [comment]
Can I close the issue?
