### ISSUE TITLE
Application registration status changes after 1 hour

### ISSUE THREAD

**Issue by ehsanmqn** [BelledonneCommunications/liblinphone#169]
Hello,
We are developing a soft-phone based on liblinphone (SDK 4.4.8). We have encountered with registration problem with our application. The problem is that the account registration status changes to UNREGISTER after 1 hour. We also tried "Expire: 60" but it didn't change anything. It will be appreciate, if you guys guide us please.

**Comment by Viish** [comment]
Please attach SDK logs showing the issue. 
Also use latest 4.4.x release.

**Comment by AlirezaDaryani** [comment]
@Viish 
It is not related to sdk log or sdk version.
Our sip accounts work well in Linphone App and never goes un-register but in our app, sip account go unregister after expire time that set in proxy file.
we need to know what method need for keep register account after expire time of registration.

**Comment by Viish** [comment]
As long as app is alive, it will auto renew the REGISTER when close to the expiration time.
Of course if app is offline it can't do it, so you should use a longer expiration time (we use 1 year).
You can also use linphone_core_refresh_register() to force the update manually.
