### ISSUE TITLE
Juddery audio

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/liblinphone#176]
Please find [attached a log](http://brian.interlinx.bc.ca/linphone-juddery-audio.txt) from linphone-android in which I am finding the audio very juddery and completely unusable.  The versions of linphone-android and linphone-sdk used there were 4f6b416b7 and 4.5.13 respectively.

On another device with linphone-android 21a00a562 and linphone-sdk 4.5.0-beta.50+c67027b the audio is much better and quite usable.

Any ideas/thoughts?

**Comment by Viish** [comment]
I can only see an ICE issue, try disabling it maybe.
But as long as you can't see a real difference in behavior between 2 version of the SDK **on the same device** it might just be a device related issue.

**Comment by brianjmurrell** [comment]
Strangely this issue seems to be not happening today.  But per BelledonneCommunications/linphone-sdk#142 I've also gotten to the bottom of why I was not getting proper ICE negotiation also.
