### ISSUE TITLE
New Registration(Subscription) through email destroys created user immediately

### ISSUE THREAD

**Issue by KARTIKNISHAD204** [BelledonneCommunications/liblinphone#187]
`
I/Register Linphone: LinphoneAccount[0x7630b76008] created with params
I/Register Linphone: LinphoneAccount[0x75be6f7808] created with params
LinphoneAccount[0x75be6f7808] created with proxy config
LinphoneAccount[0x75d81ba508] created with params
LinphoneAccount[0x75d81ba508] created with proxy config
W/Register Linphone: Bad proxy address: it is not in the list !
I/Register Linphone: Core callbacks [0x75be9b0140] registered on core [0x7630f84600]
I/Register Linphone: LinphoneAccount[0x75d81ba508] destroyed
I/Register Linphone: LinphoneAccount[0x75be6f7808] destroyed`

 .
I am trying to register a user on linphone sip account from same credential as in  my app 
as we register on   @@https://www.linphone.org/freesip/home . I have wasted 3 days on registration process .
Cant find any example code to register a user , the linphone-android have registration from phone number and 
remote configuration  only .
I have implemented  example code from this https://linphone.org/releases/docs/liblinphone/3.11.1/c/group__registration__tutorials.html link but it have  totally deprecated code . 
I have used below code to register a user , but It is showing Bad Sip address . 
If any of you have implemented  registration on linphone sip account from same email and password from your app .Please help 
@Viish 

Major issue is Linphone didn't provide example code for user registration from email , docs are unclear, and example codes are deprecated ,  Please provide code for registration same as incoming call , and outgoing  ie:-
https://gitlab.linphone.org/BC/public/tutorials
`  
    public fun stackRegistartion(callback: Activity){

        val factory = Factory.instance()

        factory.setDebugMode(true, "Register Linphone")

        var  core = factory.createCore(null, null, callback)

        val username = "uniqueusername"

        val email = "unique@email.com"

        val domain = "sip.linphhone.org"
        val displayName =  username;
        val port = "5060";
        val password =  "XXXXXXXX"
        val accountCreator: AccountCreator = core.createAccountCreator("https://subscribe.linphone.org:444/wizard.php")
        accountCreator.username = username
        accountCreator.email =email
        accountCreator.domain = domain
        accountCreator.password = password
        accountCreator.displayName = displayName
        accountCreator.transport = TransportType.Tls //Tls,Tcp,Dtls
        accountCreator.createProxyConfig();
        core.defaultProxyConfig = accountCreator.createProxyConfig();
        running = true;
        while (running) {
            core.iterate(); // first iterate initiates registration
            sleep(50);
        }
    }`

**Comment by Viish** [comment]
> Cant find any example code to register a user

We have tutorials available here: https://gitlab.linphone.org/BC/public/tutorials

> the linphone-android have registration from phone number and
remote configuration only .

No, you can login any SIP account in linphone-android app.

Your issue seems to be you don't add the proxy config to the Core.
Make the following changes:
```
val proxyConfig = accountCreator.createProxyConfig()
core.addProxyConfig(proxyConfig)
core.defaultProxyConfig = proxyConfig
```

**Comment by KARTIKNISHAD204** [comment]
Hi , Is I am doing it right , do I have to  initialize linphone core by
fetching rar resource file ie-: linphonerc_default   ,linphonerc_factory .
adding proxy config is not helping , Do i have to add sleep to wait for
registration , I have seen so many deprecated codes for registration ,
nothing is working , please share the steps or example code to register a
user by email on linphone sip server , same as
https://www.linphone.org/freesip/home

**Comment by Viish** [comment]
Here's the best sample for that: https://gitlab.linphone.org/BC/public/tutorials/-/blob/master/android/kotlin/1-AccountLogin/app/src/main/java/org/linphone/accountlogin/AccountLoginActivity.kt

**Comment by KARTIKNISHAD204** [comment]
This only work for login , if you have pre registered credentials , I can
not create subscription from this code , please see this code , [image:
Screenshot from 2021-09-20 16-00-26.png][image: Screenshot from 2021-09-20
16-03-19.png]

**Comment by Viish** [comment]
Then check how we create account on our free sip from our apps using AccountCreator object: https://github.com/BelledonneCommunications/linphone-android/blob/master/app/src/main/java/org/linphone/activities/assistant/viewmodels/EmailAccountCreationViewModel.kt

**Comment by KARTIKNISHAD204** [comment]
HI , Thank you for your response, Now I am able to Register a user on
linphone , but after receiving a email , On tapping authentication link ,
it is creating server error,
Is it necessary to open authentication link from email , I want to register
a user with that authentication button click , what things i have to do to
authenticate a register user directly without link click

**Comment by Viish** [comment]
> Is it necessary to open authentication link from email , I want to register
a user with that authentication button click , what things i have to do to
authenticate a register user directly without link click

You can't do that using our accounts database, but if you set up your own SIP server with your own accounts you will be able to do it.

**Comment by KARTIKNISHAD204** [comment]
I will  set up my own flexisip server. please help me with the
documentation or any guide which i need to follow ,
please note - right now i have implemented all the functionality using
linphone sdk with open flexisp server of yours .I am in doubt if setting up
my server will work the same as your live server.

**Comment by Viish** [comment]
> please help me with the
documentation or any guide which i need to follow

Between the [wiki](https://wiki.linphone.org/xwiki/wiki/public/view/Main/) and the [account manager](https://gitlab.linphone.org/BC/public/flexisip-account-manager) README you should manage to install and configure your own.

> I am in doubt if setting up
my server will work the same as your live server.

Why would it be different? We are using flexisip as well for our sip.linphone.org service.
