### ISSUE TITLE
How to get the Push Notification VoIP payload (iOS)

### ISSUE THREAD

**Issue by mircoiplabs** [BelledonneCommunications/liblinphone#210]
### Context

I use Linphone for my VoIP application.

### General information

- Device: generic iPhone
- OS: iOS 15
- Version of the App: 4.6.2
- Version of the SDK: latest

### Expected behaviour

I want to get the Push Notification VoIP payload with informations like "display-name", but since PushKit is hidden in the SDK I have troubles to access the push payload... 

Are there any functions to get the Push informations?

### To Reproduce

Receiving a push VoIP notification, which is managed in the SDK

**Comment by Viish** [comment]
Hi,

You can use the following callback added into 5.2 SDK: https://download.linphone.org/snapshots/docs/liblinphone/latest/swift/Classes/CoreDelegateStub.html#/s:10linphonesw12CoreDelegateP26onPushNotificationReceived4core7payloadyAA0B0C_SStF
