### ISSUE TITLE
[Bug]: Unsupported Media Type (IMDN perhaps)?

### ISSUE THREAD

**Issue by brianjmurrell** [BelledonneCommunications/liblinphone#215]
### Context

I actually use linphone-android, which is a consumer of this library.

### General information

- Device: Phone
- OS: Android 12.1
- Version of the App: linphone-android 4.6.12
- Version of the SDK: 5.1.51

### Expected behaviour

Send SIP MESSAGE from linphone-android to Asterisk PBX.

### To Reproduce

After configuring the Android client as a SIP client on an Asterisk server, try sending a SIP SMS message.

### Additional context

SIP MESSAGE from linphone-android:

```
MESSAGE sip:[redacted] SIP/2.0
Via: SIP/2.0/TCP 10.75.24.121:47446;branch=z9hG4bK.oOWg7575x;rport
From: <[redacted]>;tag=gdLM-qmf3
To: sip:[redacted]
CSeq: 21 MESSAGE
Call-ID: KHZPKeE6FD
Max-Forwards: 70
Route: <sip:[redacted];transport=tcp;lr>
Supported: replaces, outbound, gruu
Date: Tue, 02 Aug 2022 15:34:33 GMT
Content-Type: message/cpim
Content-Length: 340
User-Agent: MyLinphoneAndroid/4.6.12.23.1+dd795532d (FRD-L04) LinphoneSDK/5.1.51 (tags/5.1.51^0)
Authorization:  Digest realm="asterisk", nonce="[redacted]", algorithm=MD5, opaque="[redacted]", username="[redacted]",  uri="sip:[redacted]", response="[redacted]", cnonce="[redacted]", nc=00000001, qop=auth

From: <sip:[redacted]>
To: <sip:[redacted]>
DateTime: 2022-08-02T15:34:33Z
NS: imdn <urn:ietf:params:imdn>
imdn.Message-ID: HjFsonRLpkim
imdn.Disposition-Notification: positive-delivery, negative-delivery, display

Content-Type: text/plain
Content-Length: 31

[redacted]
```

and the response back from Asterisk:

```
SIP/2.0 415 Unsupported Media Type
Via: SIP/2.0/TCP 10.75.24.121:47446;rport=47446;received=[redacted];branch=z9hG4bK.oOWg7575x
Call-ID: KHZPKeE6FD
From: <sip:[redacted]>;tag=gdLM-qmf3
To: <sip:[redacted]>;tag=z9hG4bK.oOWg7575x
CSeq: 21 MESSAGE
Server: Asterisk PBX 18.12.1
Content-Length:  0


```

Which I suspect is due to the IMDN stuff in the SIP MESSAGE request.

So how can I, using linphone-android, disable this IMDN stuff?

**Comment by Viish** [comment]
Hi,

You  can the following in your config file (using remote provisioning for example):
```
[sip]
im_notif_policy=none
```

**Comment by brianjmurrell** [comment]
I appear to have that set to `none` already:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://www.linphone.org/xsds/lpconfig.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">
  <section name="sip">
...
    <entry name="im_notif_policy" overwrite="true">none</entry>
...
```

and still experiencing the above behaviour.

**Comment by Viish** [comment]
> Is this a setting that is exposed in some way in the settings UI to confirm that it is actually none?

No, it's not. However you can use the "view config file" option from the secret menu (dial #1234# on the keypad) to see your config file and confirm this is properly set.

**Comment by brianjmurrell** [comment]
Yeah, that secret view config file confirms that:
```ini
[sip]
  im_notif_policy=none
```

**Comment by Viish** [comment]
I just tried and it works fine on my device:
```
<config xsi:schemaLocation="http://www.linphone.org/xsds/lpconfig.xsd lpconfig.xsd">
<section name="sip">
<entry name="im_notif_policy" overwrite="true">none</entry>
</section>
</config>
```

Can you attach logs please?

**Comment by brianjmurrell** [comment]
> I just tried and it works fine on my device:

Meaning that you confirmed that you don't have any IMDN headers, etc. in your SIP `MESSAGE` when you have `im_notif_policy=none`?

[Log](http://brian.interlinx.bc.ca/linphone-imdn-failure.txt) for your inspection.

**Comment by Viish** [comment]
Thanks for the logs.

The issue you're having isn't due to IMDNs but to CPIM.
IMDN are "Instant Messaging Delivery Notification" messages, CPIM is an envelope for a SIP message.

What's weird is CPIM isn't enabled by default in "basic" chat rooms, only for end-to-end and/or group chat rooms (which both require the remote server to be a Flexisip instance).
Can you check your proxy config in the config file to see if there is a `cpim_in_basic_chat_rooms_enabled` key and if there is, what it's value is?

**Comment by brianjmurrell** [comment]
I do have `[sip]` -> `use_cpim=1` as well as `[proxy_default_values]
` -> `cpim_in_basic_chat_rooms_enabled=1` as well as `[proxy_0]` -> `cpim_in_basic_chat_rooms_enabled=1`.

**Comment by Viish** [comment]
> as well as [proxy_0] -> cpim_in_basic_chat_rooms_enabled=1

That's the issue, even though I don't know how it got enabled...
To fix it, add to your remote provisioning an entry to override it to 0.

**Comment by brianjmurrell** [comment]
But you saw my followup that I DO NOT have `cpim_in_basic_chat_rooms_enabled` set to any value in my remote provisioning config, yes?  So most certainly Linphone is adding this to the proxy entry, isn't it?

This seems like it's a bug doesn't it?

**Comment by brianjmurrell** [comment]
OK.  Now it **is** a bug.  I have added to my remote config:

```
  <section name="proxy_0">
    <entry name="cpim_in_basic_chat_rooms_enabled" overwrite="true">0</entry>
```

and after I fetch that config and then check the config using the secret menu, it's back to being `1`.

**Comment by brianjmurrell** [comment]
Any idea how long this sort of thing will take to fix and make it into a published version of liblinphone?

**Comment by Viish** [comment]
Actually I don't think there is an issue in the app itself.
Do you have, in your remote provisioning, set or changed the `[app] default_domain=` setting?
That's the only way I can explain the `cpim_in_basic_chat_rooms_enabled` to be forced to 1.
I don't have access to your logs anymore but do you see `[Context] CPIM allowed in basic chat rooms` in the logs?

**Comment by brianjmurrell** [comment]
> Do you have, in your remote provisioning, set or changed the `[app] default_domain=` setting?

No.  That setting doesn't exist at all anywhere in my remote provisioning config.

> I don't have access to your logs anymore but do you see `[Context] CPIM allowed in basic chat rooms` in the logs?

No.

**Comment by Viish** [comment]
Can you try latest 4.7.0 beta please and tell me if the same happens? https://download.linphone.org/snapshots/android/linphone-android-debug-4.7.0-beta.54+b067f8378.apk

**Comment by Viish** [comment]
I understand that using a beta version might be risky, but in this case the current beta version will be published as the release on Monday (we are simply waiting for iOS app to be ready as well to publish both of them at the same time).

**Comment by brianjmurrell** [comment]
4.7.0-beta does seem to resolve this.

**Comment by Viish** [comment]
Perfect, thanks!
