### ISSUE TITLE
[Bug]: Crash on core initialization (Unable to load VCARD grammar)

### ISSUE THREAD

**Issue by IMAN4K** [BelledonneCommunications/liblinphone#222]
### Context

I use the linphone-sdk in my testbed environment with sip.linphone.org for my company. I want to do some simple API call to use the SDK but at the early stage construction of `linphone::Core` causes a segmentation fault.

### General information

- Device: desktop PC
- OS: Windows 10 x64
- Version of the SDK: 4.5.5

### Expected behaviour

I wanted to do a simple API call or core initialization to work with SDK.

### To Reproduce

1. Download SDK 4.5.5 for win32 from https://download.linphone.org/releases/windows/sdk
2. Extract on some location
3. Inform your IDE or CMake to find it (add to the path)
4. try to create a new `linphone::Core` with `linphone::Factory::get()->createCore("", "", nullptr)`

### Additional context

```
1  abort                                 ucrtbase                0x75c7eddb 
2  bctbx_logv                            logging.c          569  0x683d9d3e 
3  bctbx_fatal                           logging.h          245  0x69bca2e7 
4  loadVcardGrammar                      vcard_grammar.cpp  25   0x69bca26f 
5  belcard::BelCardParser::BelCardParser belcard_parser.cpp 40   0x69b82243 
6  belcard::BelCardParser::getInstance   belcard_parser.cpp 34   0x69b82886 
7  linphone_vcard_context_new            vcard.cc           46   0x6b1aaaf2 
8  linphone_core_init                    linphonecore.c     2905 0x6b169f3a 
9  _linphone_core_new_with_config        linphonecore.c     3014 0x6b1676f4 
10 _linphone_core_new_with_config        linphonecore.c     3019 0x6b170059 
11 LinphonePrivate::Factory::_createCore factory.cpp        132  0x6b06e15c 
12 LinphonePrivate::Factory::createCore  factory.cpp        179  0x6b06e467 
13 linphone_factory_create_core_3        c-factory.cpp      73   0x6af748e6 
14 linphone::Core::createAddress         liblinphone__           0x7335349c 
15 main                                  main.cpp           12   0xb219a8   
16 invoke_main                           exe_common.inl     78   0xb24063   
17 __scrt_common_main_seh                exe_common.inl     288  0xb23eb7   
18 __scrt_common_main                    exe_common.inl     331  0xb23d4d   
19 mainCRTStartup                        exe_main.cpp       17   0xb240e8   
20 BaseThreadInitThunk                   KERNEL32                0x764e00f9 
21 RtlGetAppContainerNamedObjectPath     ntdll_77d20000          0x77d87bbe 
22 RtlGetAppContainerNamedObjectPath     ntdll_77d20000          0x77d87b8e 

```

### SDK logs URL

https://pastebin.com/Nsjq3CAF

**Comment by Viish** [comment]
Hi,

First of all, you shouldn't use 4.5.5 SDK as it is old and not maintained anymore but 5.2.6.
Then, you must tell the app where the grammars are located.
From the download SDK dir, it's in `linphone-sdk/desktop/share/belr/grammars`.
Try to define the `BELR_GRAMMARS_DIR` to the right value.

Cheers,

**Comment by IMAN4K** [comment]
Hi dear @Viish 

We have few problems and crashes due to the grammar absence like the one that I mentioned in this issue. (for example another crash happens on incoming call which throw out `Unable to load SDP grammar`)
So far I've added `BELR_GRAMMARS_DIR` as a runtime environment variable but the application couldn't still locate the VCARD grammar!
So did I miss something?

Regards.
