### ISSUE TITLE
[Question]: C# Wrapper 

### ISSUE THREAD

**Issue by yeatttttt** [BelledonneCommunications/liblinphone#230]
### Context

i have a project on C# for Win/Linux, and i really don't know how to use it for c# rn, please, help me

### General information

- Device:
- OS:
- Version of the App:
- Version of the SDK:

### Expected behaviour

I wanted to do a simple call with the Linux client calling the Android phone. However, the phone doesn't ring when it is asleep.

**Comment by Viish** [comment]
How about reading https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Linphone%20C%23%20wrapper/ and taking a look at our [tutorials](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/uwp/cs) ?

**Comment by yeatttttt** [comment]
> How about reading https://wiki.linphone.org/xwiki/wiki/public/view/Lib/Linphone%20C%23%20wrapper/ and taking a look at our [tutorials](https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/uwp/cs) ?

i write on Avalonia, it's not UWP

**Comment by Viish** [comment]
C# wrapper is the same for UWP, Xamarin, etc... so you should be able to use it for Avalonia as well.

**Comment by yeatttttt** [comment]
> C# wrapper is the same for UWP, Xamarin, etc... so you should be able to use it for Avalonia as well.

So, i tried that
Download Nuget Package, and then install it to the solution. It works on UWP tutorial project, but not at mine

**Comment by yeatttttt** [comment]
> C# wrapper is the same for UWP, Xamarin, etc... so you should be able to use it for Avalonia as well.

![изображение](https://github.com/BelledonneCommunications/liblinphone/assets/91808439/0115dbba-ef82-4f6e-bef4-c1b85a507f18)

**Comment by Viish** [comment]
@yeatttttt you tried to use 5.1.0-beta, try with latest 5.2 release instead.

**Comment by yeatttttt** [comment]
> @yeatttttt you tried to use 5.1.0-beta, try with latest 5.2 release instead.

where can i find 5.2 release NuGet package?

**Comment by Viish** [comment]
@yeatttttt https://gitlab.linphone.org/BC/public/linphone-sdk/-/packages

**Comment by yeatttttt** [comment]
> @yeatttttt https://gitlab.linphone.org/BC/public/linphone-sdk/-/packages

ty! 5.2.* or only 5.2?

**Comment by Viish** [comment]
Use either 5.2.99 or 5.2.+ to be automatically updated to the latest, as you prefer.

**Comment by yeatttttt** [comment]
![image](https://github.com/BelledonneCommunications/liblinphone/assets/91808439/6d0cca1f-b74d-4f0c-9d26-116a54ec150b)
There is a such problem

**Comment by yeatttttt** [comment]
> Use either 5.2.99 or 5.2.+ to be automatically updated to the latest, as you prefer.

And it's work on UWP again, but not on Avalonia

**Comment by yeatttttt** [comment]
> Use either 5.2.99 or 5.2.+ to be automatically updated to the latest, as you prefer.

ok i fixed that, last question - is that corssplatform? if i develop an application on windows for Linux, will it work on it?

**Comment by Viish** [comment]
Yes it should. Also for MacOSX.

**Comment by yeatttttt** [comment]
> Yes it should. Also for MacOSX.

System.IO.FileNotFoundException: Could not load file or assembly 'CsWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Не удается найти указанный файл.
File name: 'CsWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
   at AvaloniaLlacot.Services.SoftPhone.Models.CoreService.Call(String uriToCall)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at AvaloniaLlacot.Services.SoftPhone.Models.CoreService.Call(String uriToCall)
   at AvaloniaLlacot.Services.SoftPhone.Models.SipClient.Call(String destination) in C:\Users\user\Desktop\avaloniallacot\AvaloniaLlacot\Services\SoftPhone\Models\SipClient.cs:line 156

**Comment by Viish** [comment]
Sorry but I can't help you more, I'm no expert on that part.
