### ISSUE TITLE
[Bug]: Dial plan error DialPlan::create("Libya", "LY", "218", 8, "00") the number of digits should be 9

### ISSUE THREAD

**Issue by aaltu008** [BelledonneCommunications/liblinphone#231]
### Context

linphone on android phone with multiple Asterisk sip server connections

### General information

- Device: Samsung Note 20 Ultra
- OS: Android
- Version of the App: Linphone
- Version of the SDK:

### Expected behaviour

I use the android app, but the number editing when the international country code for Libya is detected removes essential digits from the number. the resulting number is missing one digit because of this code:  DialPlan::create("Libya", "LY", "218", 8, "00") in the dial plan library. the correct number of digits is 9 . For example a number without a country code should look like  09x xxx xxxx the number with country code should look like  +218 9x xxx xxxx. So the correct number of digits should be 9 instead of 8.

The bug is in the file (https://github.com/BelledonneCommunications/liblinphone/blob/5c4308984f375fcaf5d1c079defb49e63628eb57/src/dial-plan/dial-plan.cpp#L102) 

Please update this as soon as you can because the application currently is unusable in Libya. Most people use international prefix with their phone book even for local numbers because of whatsapp and travel!

### To Reproduce

1. Store a number in this format +218 9x xxx xxxx in your contacts and call it from linphone, the called number will be edited to become +218x xxx xxx missing the essential digit 9. The call will not be processed by the mobile and fixed operator and the number busy signal is retuned.

**Comment by Viish** [comment]
Hi,

Thanks for the report, I'll fix it first thing monday morning.

Cheers,

**Comment by Viish** [comment]
Hi again,

Issue has been fixed in 5.2.104 release as well as in master branch.

Cheers,
