### ISSUE TITLE
Increase LDAP search limit for MagicSearch

### ISSUE THREAD

**Issue by m0kka** [BelledonneCommunications/liblinphone#240]
Hi, I am using Linphone 5.2.3 from the Play Store on Android.

For the sake of experimentation, I added an LDAP server to use as an address book for Linphone, which has worked great so far! However, I noticed that the magic search (when switching to the contacts list in the app) only returns 31 entries at most, no matter the limits that I had set for LDAP search results in the settings.

Upon further investigation, it seems that the magic search feature has a hard-coded limit of 30 (+1) for LDAP search results. It would be fantastic if this limit could be increased , or if Magic Search would use the LDAP search limit that is available in the app's settings.

The line with the hard-coded limit is found here: https://github.com/BelledonneCommunications/liblinphone/blob/3e402a02bcf7922c8cc35a96ce623028cbd711de/src/search/magic-search.cpp#L53

I'm looking forward to your thoughts on this and wish you some relaxing Easter days!

**Comment by m0kka** [comment]
At a second glance this may also be a bug/possible solution in https://github.com/BelledonneCommunications/liblinphone/blob/3e402a02bcf7922c8cc35a96ce623028cbd711de/src/ldap/ldap-contact-provider.cpp#L357
as the limit set in the app settings is only used if it is < 30 when MagicSearch is used

**Comment by Viish** [comment]
Hi @m0kka,

Both those limits are configurable:

- https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/LdapParams.html#setMaxResults(int)
- https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/MagicSearch.html#setSearchLimit(int)

Cheers!

**Comment by Viish** [comment]
You can also disable the limit in MagicSearch: https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/MagicSearch.html#setLimitedSearch(boolean)

**Comment by m0kka** [comment]
Many thanks for the quick reply!
I guess this is more of a feature request for the linphone android app, then, such that the app actually properly passes on the ldap search limit to magic search. I'll continue my quest c:

**Comment by Viish** [comment]
@m0kka,

The Android app is already configured to have no limit on magic search results, and the max LDAP results can be configured in-app.

Cheers,

**Comment by m0kka** [comment]
Well, my findings are different, I have checked my ldap logs and the app never sends a search request with a limit > 30, disregarding whatever I enter in the settings. 
The ldap search limit only applies if I choose a value that is below 30

**Comment by Viish** [comment]
Ok then there is an issue with the unlimited search mode of the magic search with LDAP then, because I double checked and it is correctly configured as unlimited in Android app: https://gitlab.linphone.org/BC/public/linphone-android/-/blob/master/app/src/main/java/org/linphone/contact/ContactsManager.kt#L63

**Comment by Viish** [comment]
Hi @m0kka,

I've created a SDK branch (based on master) with a fix for your issue if you want to test it: fix/ldap_search_results_limit

Cheers,

**Comment by m0kka** [comment]
Thank you many times for your help, this looks very promising! I shall test this locally as soon as can be and wish you all the best!

**Comment by Viish** [comment]
Hi @m0kka,

I've merged the fix in SDK master branch, version is 5.4.0-alpha.140.
Build & maven upload are in progress.

Cheers,
