### ISSUE TITLE
About instant chat questions

### ISSUE THREAD

**Issue by LoyaiHai** [BelledonneCommunications/liblinphone#242]
Hi 
@Viish 
Now I want to use the function of instant chat. In the android client, I have implemented the interface callbacks of onChatRoomRead, onMessagesReceived, onMessageReceived. But now the problem is that I sent an instant message using MicroSIP and did not receive it.
What I want to ask now is: Do I have to go through the contact list, select a member, create a chat room, so that I can receive this message in the current callback interface?

**Comment by AndreaGianarda** [comment]
Hi,

Have you by any chance set your core as a conference server?

Andrea

**Comment by LoyaiHai** [comment]
@AndreaGianarda 
I never set up my server as a meeting server, but it is true that my server can start meetings
The point here is that meetings don't come with linphone, but with freeswitch's meeting feature

**Comment by AndreaGianarda** [comment]
@LoyaiHai 

According your logs, you are passing true when calling setConferenceServerEnabled (https://download.linphone.org/releases/docs/liblinphone/5.3/java/org/linphone/core/Core.html#setConferenceServerEnabled(boolean)) therefore your android client expects the chatroom to be created beforehand.

When you receive a message, you are hitting the else statement here: https://gitlab.linphone.org/BC/public/liblinphone/-/blob/master/src/core/core-chat-room.cpp#L1012

Hope this helps,

Andrea

**Comment by LoyaiHai** [comment]
@AndreaGianarda 
you are right,i have setConferenceServerEnabled(true).
so,  If I want to receive an instant chat message, can I change true to false？

**Comment by AndreaGianarda** [comment]
yep

**Comment by LoyaiHai** [comment]
@Viish 
yes, i have already receive the message
<img width="680" alt="收到" src="https://github.com/BelledonneCommunications/liblinphone/assets/32878163/6a17a82b-db76-445a-b1b1-2b53c33ae89e">
now, the new question: 
If I want to send a message to each other(1004), do I need to create a chat room? Or just create the chatroom and populate it with data

**Comment by LoyaiHai** [comment]
@Viish @AndreaGianarda 
Another question that just came to my mind is if I receive this content, what interface do I need to call to change this unread state to read? I see an issue with someone asking for access

**Comment by Viish** [comment]
Please read out chat related tutorials: https://gitlab.linphone.org/BC/public/tutorials/-/tree/master/android/kotlin/5-BasicChat

**Comment by LoyaiHai** [comment]
@Viish & @AndreaGianarda 
i got it
thank you
