### ISSUE TITLE
[Bug]: Incorrect number length(s) in dialplan

### ISSUE THREAD

**Issue by vhartikainen** [BelledonneCommunications/liblinphone#244]
### Context

This library is included in the linphone-sdk we're using in our project.

### General information

Device agnostic

### Expected behaviour

1. Retrieve Dialplan for a Finnish mobile number
2. Check nationalNumberLength
3. Expect to return a correct length based on ITU-T numbering plans

### To Reproduce

1. Retrieve Dialplan for a Finnish Number: +3584012345678
2. Expect to return nationalNumberLength=10 (there could be longer numbers in Finland too)
3. Instead, 9 is returned, which will lead to incorrect number formatting (i.e. +358012345678)

Additional example:
1. https://paradisehotelnorfolk.com/ - +672322177
2. Will not work

### Additional context

Suspect other nationalNumberLengths are too outdated. These should be compared against ITU-T standards instead of potentially inaccurate wikipedia sources. This might lead to problems with customers dialing phonenumbers.

See e.g. https://www.itu.int/dms_pub/itu-t/oth/02/02/T02020000490003PDFE.pdf

See: https://en.wikipedia.org/wiki/List_of_mobile_telephone_prefixes_by_country
Seems to have Finnish Mobile numbers with lengths: 8-11

Clearly dialplan data is outdated.
https://github.com/BelledonneCommunications/liblinphone/blob/9ed7db96df828ee21e6fb4d233b0667356123e80/src/dial-plan/dial-plan.cpp#L146
https://github.com/BelledonneCommunications/liblinphone/blob/9ed7db96df828ee21e6fb4d233b0667356123e80/src/dial-plan/dial-plan.cpp#L87

**Comment by Viish** [comment]
Hi @vhartikainen,

This was fixed in commits 3ab0379cd15fd313c06ca594a28759c70ca6606c & 8688b2a506225b41652a4a3962fa32fb2e726bcd

Cheers,
